services:
  rust:
    build:
      context: ../Rust/.devcontainer
      dockerfile: Dockerfile
    volumes:
      - ../Rust:/workspace:cached
    command: sleep infinity
    user: loic
    environment:
      - LIBCLANG_PATH=/usr/lib/x86_64-linux-gnu
      - ROCKSDB_LIB_DIR=/usr/lib/x86_64-linux-gnu
      - ROCKSDB_INCLUDE_DIR=/usr/include
    networks:
      - rust-network

networks:
  rust-network:
    driver: bridge