services:
  php:
    build:
      context: ../PHP
      dockerfile: ../PHP/.devcontainer/Dockerfile
    volumes:
      - ../PHP:/workspace:cached
    command: sleep infinity
    ports:
      - "8000:8000"
      - "443:443"
    depends_on:
      - mysql
      - ldap
    # environment:
    #   - DATABASE_URL=mysql://mariadb:mariadb@mysql:3306/mariadb?serverVersion=8.0

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      # MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: mariadb
      UPLOAD_LIMIT: 20M
    ports:
      - "80:80"
    depends_on:
      - mysql

  ldap:
    image: osixia/openldap:1.5.0  # Version stable et récente
    container_name: dev-ldap
    # build:
    #   context: ../PHP
    #   dockerfile: ../PHP/ldap/Dockerfile
    environment:
        LDAP_ORGANISATION: "MyCompany"
        LDAP_DOMAIN: "mycompany.com"
        LDAP_ADMIN_PASSWORD: "adminpass"
        LDAP_CONFIG_PASSWORD: "configpass"
        LDAP_TLS: "false"
        #LDAP_SEED_INTERNAL_LDIF_PATH: /container/service/slapd/assets/*.ldif  # Importe tous les fichiers .ldif
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./ldap-data:/var/lib/ldap
      - ./ldap-config:/etc/ldap/slapd.d
volumes:
  mysql-data: