services:
  php:
    build:
      context: ../PHP
      dockerfile: ../PHP/.devcontainer/Dockerfile
    volumes:
      - ../PHP:/workspace:cached
    command: sleep infinity
    ports:
      - "8000:8000"
      - "443:443"
    depends_on:
      - mysql
    # environment:
    #   - DATABASE_URL=mysql://mariadb:mariadb@mysql:3306/mariadb?serverVersion=8.0

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      # MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: mariadb
      UPLOAD_LIMIT: 20M
    ports:
      - "80:80"
    depends_on:
      - mysql

  ldap:
    image: osixia/openldap:1.5.0  # Version stable et récente
    container_name: simulated-ldap
    environment:
      LDAP_ORGANISATION: "MyCompany"  # Nom de ton organisation (DC)
      LDAP_DOMAIN: "mycompany.com"    # Domaine LDAP (ex. dc=mycompany,dc=com)
      LDAP_ADMIN_PASSWORD: "adminpass"  # Mot de passe admin (change-le pour la sécu)
      LDAP_CONFIG_PASSWORD: "configpass"  # Mot de passe pour la config (optionnel, mais requis)
      LDAP_TLS: "false"  # Désactive TLS pour simplicité (active-le si besoin avec certs)
      LDAP_SEED_INTERNAL_LDIF_PATH: /container/service/slapd/assets/*.ldif
    ports:
      - "389:389"  # Port LDAP standard (non sécurisé)
      - "636:636"  # Port LDAPS (sécurisé, si activé)
    volumes:
      - ./ldap-data:/var/lib/ldap  # Persiste les données LDAP
      - ./ldap-config:/etc/ldap/slapd.d  # Persiste la config
      - ../PHP/ldap/ldif:/container/service/slapd/assets

volumes:
  mysql-data: