services:
  php:
    build:
      context: ../PHP
      dockerfile: ../PHP/.devcontainer/Dockerfile
    volumes:
      - ../PHP:/workspace:cached
    command: sleep infinity
    ports:
      - "8000:8000"
      - "443:443"
    depends_on:
      - mysql
    # environment:
    #   - DATABASE_URL=mysql://mariadb:mariadb@mysql:3306/mariadb?serverVersion=8.0

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      # MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: mariadb
      UPLOAD_LIMIT: 20M
    ports:
      - "80:80"
    depends_on:
      - mysql

  ldap:
    image: bitnami/openldap:2  # Version stable et récente
    container_name: dev-ldap
    build:
      context: ../PHP
      dockerfile: ../PHP/ldap/Dockerfile
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpass
      - LDAP_USERS=john.doe
      - LDAP_PASSWORDS=password123
      - LDAP_ROOT=dc=mycompany,dc=com
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./ldap-data:/bitnami/openldap

volumes:
  mysql-data: