version: '3.8'

services:
  dev:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - ldap
    networks:
      - default

  ldap:
    image: bitnami/openldap:latest
    env_file:
      - ../.env  # Charge le fichier .env
    environment:
      LDAP_ROOT: ${LDAP_ROOT}
      LDAP_ADMIN_USERNAME: ${LDAP_ADMIN_USERNAME}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_CUSTOM_LDIF_DIR: ${LDAP_CUSTOM_LDIF_DIR}
      LDAP_LOGLEVEL: ${LDAP_LOGLEVEL}
      LDAP_SKIP_DEFAULT_TREE: ${LDAP_SKIP_DEFAULT_TREE}
    volumes:
      - ../ldif:/ldifs:ro
      - ldap-data:/bitnami/openldap/data
    ports:
      - "389:1389"
    networks:
      - default

volumes:
  ldap-data:

networks:
  default: